version: "3.3"
services:
  react:
    container_name: djenitor-frontend
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${REACT_PORT}:80"
    volumes:
      - react-app:/app
#   express:
#     container_name: djenitor-backend
#     restart: always
#     build: 
#       context: ./backend
#       dockerfile: Dockerfile
#     ports: 
#       - "${EXPRESS_PORT}:5000"
#     volumes:
#       - express-app:/app
volumes:
  react-app:
#   express-app: