version: "3.3"
services:
  react:
    container_name: djenitor-frontend
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${REACT_PORT}:80"
    volumes:
      - react-app:/app
    depends_on: 
      - database
  express:
    container_name: djenitor-backend
    restart: always
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports: 
      - "${EXPRESS_PORT}:5000"
    volumes:
      - express-app:/app
    depends_on: 
      - database
  database:
    container_name: djenitor-database
    restart: always
    image: mongo
    ports: 
      - "${MONGO_PORT}:27017"
    volumes: 
      - mongo-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
volumes:
  react-app:
  express-app:
  mongo-db: